name: Build Releases
on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        type: string
jobs:
  build-macos:
    runs-on: macos-latest
    env:
      BUILD_OS: "macos"
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4

      - name: Install GNU tar
        if: runner.os == 'macOS'
        run: |
          brew install gnu-tar
          # echo "::add-path::/usr/local/opt/gnu-tar/libexec/gnubin"
          echo "/usr/local/opt/gnu-tar/libexec/gnubin" >> $GITHUB_PATH

      - name: Build release
        shell: bash
        run: |
          bash ./nb/build_macos.sh
      
      - name: Package
        shell: bash
        run: |
          tar cvfJ release/nbng.macos.arm64.tar.xz release/nbng
          rm release/nbng

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: release/*
          prerelease: ${{ contains(github.ref_name, '-') }}
          tag_name: ${{ inputs.tag || github.ref_name }}
